"""The manifest published alongside a model artifact.

`bundle.json` is the only thing that travels with a `.onnx` file, and it is the boundary
where Python hands the model to TypeScript. It records what the artifact is, which heads
carry trained weights, and the statistics needed to turn the nutrition outputs back into
kilocalories.

Building it lives here rather than inline in the export script so that both sides of that
boundary can be tested against one definition. `shared/bundle.example.json` is generated by
this module, committed, and read by the TypeScript client's own tests. If a key is renamed
on this side, the Python test fails; if the client cannot parse the result, the TypeScript
test fails. That was not previously true, and the two sides had in fact drifted: this module
emits snake_case and the client was written expecting camelCase, so no real manifest would
ever have produced nutrition figures.
"""

from __future__ import annotations

from typing import Any

SCHEMA_VERSION = 2


def build_bundle(
    *,
    artifact: dict[str, Any],
    heads_trained: dict[str, bool],
    provenance: dict[str, Any],
    quantization: dict[str, Any] | None,
    generated_utc: str,
    contract_path: str = "shared/model_meta.json",
) -> dict[str, Any]:
    """Assemble the manifest.

    ``target_transform`` is lifted out of provenance and given a top-level home. It is not
    provenance: without it the nutrition outputs are unitless numbers rather than
    kilocalories, so it is load-bearing for any client and should not be buried among
    fields that only describe how the model was made.
    """
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_utc": generated_utc,
        "contract": contract_path,
        "artifact": artifact,
        "heads_trained": {
            "logits": bool(heads_trained["logits"]),
            "nutrition_quantiles": bool(heads_trained["nutrition_quantiles"]),
        },
        "target_transform": provenance.get("target_transform"),
        "provenance": provenance,
        "quantization": quantization,
    }
