/**
 * Reading the manifest the exporter publishes.
 *
 * `bundle.json` is written by Python and is snake_case throughout. This module is the only
 * place that knows that, so the rest of the library works in the camelCase shape the
 * public types declare.
 *
 * It exists because the two sides had drifted. `ModelBundle` was written expecting
 * camelCase and every test constructed one by hand, so a real manifest had never been fed
 * through the library. `bundle.headsTrained` would have been `undefined`, the untrained
 * check would have read it as false, and nutrition would have been withheld for every
 * model regardless of how it was trained. It fails safe, which is exactly why it could
 * have shipped unnoticed.
 *
 * `shared/bundle.example.json` is generated by the Python builder and parsed by this
 * module's tests, so the boundary is now checked from both sides.
 */

import type { ConformalOffsets, ModelBundle, TargetTransform } from "./types";

/** Manifest versions this library understands. */
export const SUPPORTED_SCHEMA_VERSIONS = [3];

type RawTransform = {
  mean?: unknown;
  std?: unknown;
  keys?: unknown;
};

type RawConformal = {
  keys?: unknown;
  offsets?: unknown;
  alpha?: unknown;
  calibration_size?: unknown;
};

type RawBundle = {
  schema_version?: unknown;
  heads_trained?: { logits?: unknown; nutrition_quantiles?: unknown };
  target_transform?: RawTransform | null;
  conformal?: RawConformal | null;
  artifact?: { name?: unknown; bytes?: unknown; sha256?: unknown };
};

const isNumberArray = (value: unknown): value is number[] =>
  Array.isArray(value) && value.every((entry) => typeof entry === "number");

const parseTransform = (raw: RawTransform | null | undefined): TargetTransform | null => {
  if (!raw) return null;

  const { mean, std, keys } = raw;
  if (!isNumberArray(mean) || !isNumberArray(std)) {
    throw new Error("bundle target_transform must carry numeric mean and std arrays");
  }
  if (!Array.isArray(keys) || !keys.every((key) => typeof key === "string")) {
    throw new Error("bundle target_transform must carry a list of target keys");
  }
  if (mean.length !== std.length || mean.length !== keys.length) {
    // Mismatched lengths would misalign the inverse transform, and every nutrition figure
    // would come back in the wrong target's units rather than failing.
    throw new Error(
      `bundle target_transform is inconsistent: ${keys.length} keys, ${mean.length} means, ` +
        `${std.length} standard deviations`,
    );
  }

  return { mean, std, keys };
};

/**
 * Parse a published `bundle.json` into the shape the library uses.
 *
 * Throws rather than filling in defaults. A manifest that cannot be read is a model whose
 * provenance is unknown, and guessing at it produces exactly the confident-but-meaningless
 * output this library is built to refuse.
 */
export const parseBundle = (raw: unknown): ModelBundle => {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("bundle must be an object; pass the parsed contents of bundle.json");
  }

  const source = raw as RawBundle;
  const version = source.schema_version;

  if (typeof version !== "number") {
    throw new Error("bundle is missing schema_version; it was not written by this exporter");
  }
  if (!SUPPORTED_SCHEMA_VERSIONS.includes(version)) {
    throw new Error(
      `bundle schema version ${version} is not supported by this package ` +
        `(understands ${SUPPORTED_SCHEMA_VERSIONS.join(", ")})`,
    );
  }

  const heads = source.heads_trained;
  if (typeof heads?.logits !== "boolean" || typeof heads?.nutrition_quantiles !== "boolean") {
    // Absence is not a claim. Defaulting either way would either withhold a usable head or
    // present an untrained one, and both are worse than saying the manifest is unreadable.
    throw new Error("bundle heads_trained must state both logits and nutrition_quantiles");
  }

  return {
    schemaVersion: version,
    headsTrained: {
      logits: heads.logits,
      nutritionQuantiles: heads.nutrition_quantiles,
    },
    targetTransform: parseTransform(source.target_transform),
    conformal: parseConformal(source.conformal),
  };
};

/**
 * Interval widening measured on held-out data, or null when the model shipped without it.
 *
 * Not optional in spirit. Raw quantiles from this model cover about 82% of the truth while
 * claiming 90%; the offsets take that to 90.5%. A bundle without them describes a model
 * whose stated confidence is wrong, which is why the schema version was raised rather than
 * this being added quietly: an older client refuses the bundle instead of silently
 * under-covering.
 */
const parseConformal = (raw: RawConformal | null | undefined): ConformalOffsets | null => {
  if (!raw) return null;

  const { keys, offsets, alpha } = raw;
  if (!isNumberArray(offsets)) {
    throw new Error("bundle conformal offsets must be an array of numbers");
  }
  if (!Array.isArray(keys) || !keys.every((key) => typeof key === "string")) {
    throw new Error("bundle conformal must name the targets its offsets apply to");
  }
  if (keys.length !== offsets.length) {
    // Zipping mismatched lists would widen the wrong target, and an interval widened by
    // another quantity's miss is worse than one that was never widened at all.
    throw new Error(
      `bundle conformal has ${keys.length} keys and ${offsets.length} offsets`,
    );
  }

  return {
    keys,
    offsets,
    alpha: typeof alpha === "number" ? alpha : 0.1,
  };
};

/** Expected size and hash of the artifact a manifest describes, when it records them. */
export type ArtifactDescriptor = {
  name: string;
  bytes: number;
  sha256: string;
};

/** Read the artifact descriptor, or null for a manifest that carries none. */
export const artifactOf = (raw: unknown): ArtifactDescriptor | null => {
  const artifact = (raw as RawBundle | null)?.artifact;
  if (!artifact) return null;

  const { name, bytes, sha256 } = artifact;
  if (typeof name !== "string" || typeof bytes !== "number" || typeof sha256 !== "string") {
    return null;
  }
  return { name, bytes, sha256 };
};
