import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { artifactOf, parseBundle } from "../bundle";
import { targetKeys } from "../contract";

const here = dirname(fileURLToPath(import.meta.url));
const sharedDir = join(here, "..", "..", "..", "..", "shared");

/**
 * The manifest the Python exporter actually produces, generated by
 * model/scripts/write_bundle_example.py and asserted against the builder by pytest.
 *
 * Parsing a real file rather than a hand-written object is the entire point of this suite.
 * Every other test in this package constructs a ModelBundle by hand, which is how a
 * camelCase-versus-snake_case mismatch survived: the library was only ever fed inputs
 * shaped the way it already expected.
 */
const published = () => JSON.parse(readFileSync(join(sharedDir, "bundle.example.json"), "utf8"));

describe("parseBundle on the published manifest", () => {
  it("reads the exporter's own output", () => {
    const bundle = parseBundle(published());

    expect(bundle.schemaVersion).toBe(3);
    expect(bundle.headsTrained.logits).toBe(true);
    expect(bundle.headsTrained.nutritionQuantiles).toBe(true);
  });

  it("recovers a usable target transform", () => {
    const bundle = parseBundle(published());

    expect(bundle.targetTransform).not.toBeNull();
    expect(bundle.targetTransform?.keys).toEqual(targetKeys);
    expect(bundle.targetTransform?.mean).toHaveLength(targetKeys.length);
  });

  it("reads the artifact descriptor", () => {
    const artifact = artifactOf(published());

    expect(artifact?.name).toMatch(/\.onnx$/);
    expect(artifact?.bytes).toBeGreaterThan(0);
    expect(artifact?.sha256).toHaveLength(64);
  });
});

describe("parseBundle rejections", () => {
  it("refuses a manifest with no schema version", () => {
    expect(() => parseBundle({ heads_trained: { logits: true, nutrition_quantiles: true } })).toThrow(
      /schema_version/,
    );
  });

  it("refuses a schema version it does not understand", () => {
    expect(() => parseBundle({ ...published(), schema_version: 99 })).toThrow(/not supported/);
  });

  it("refuses a manifest that omits a head", () => {
    const raw = published();
    delete raw.heads_trained.nutrition_quantiles;

    // Absence is not a claim. Defaulting to true would present an untrained head as real;
    // defaulting to false would withhold a working one. Neither is better than saying so.
    expect(() => parseBundle(raw)).toThrow(/heads_trained/);
  });

  it("refuses a transform whose arrays disagree in length", () => {
    const raw = published();
    raw.target_transform.std = raw.target_transform.std.slice(1);

    // Silently zipping these would misalign the inverse transform and report every target
    // in another target's units, which looks like a badly trained model.
    expect(() => parseBundle(raw)).toThrow(/inconsistent/);
  });

  it("refuses a non-object", () => {
    expect(() => parseBundle("bundle.json")).toThrow(/must be an object/);
    expect(() => parseBundle(null)).toThrow(/must be an object/);
  });
});

describe("parseBundle on an untrained nutrition head", () => {
  it("carries the flag through rather than dropping it", () => {
    const raw = published();
    raw.heads_trained.nutrition_quantiles = false;
    raw.target_transform = null;

    const bundle = parseBundle(raw);

    expect(bundle.headsTrained.nutritionQuantiles).toBe(false);
    expect(bundle.targetTransform).toBeNull();
  });
});

describe("conformal offsets", () => {
  it("are read from the published manifest", () => {
    const bundle = parseBundle(published());

    expect(bundle.conformal).not.toBeNull();
    expect(bundle.conformal?.keys).toEqual(targetKeys);
    expect(bundle.conformal?.offsets).toHaveLength(targetKeys.length);
  });

  it("are null for a model that shipped without them", () => {
    const raw = published();
    raw.conformal = null;
    expect(parseBundle(raw).conformal).toBeNull();
  });

  it("refuse keys and offsets of different lengths", () => {
    // Zipping mismatched lists would widen the wrong target, and an interval widened by
    // another quantity's miss is worse than one never widened at all.
    const raw = published();
    raw.conformal.offsets = raw.conformal.offsets.slice(1);
    expect(() => parseBundle(raw)).toThrow(/keys and/);
  });

  it("refuse non-numeric offsets", () => {
    const raw = published();
    raw.conformal.offsets = ["wide", "wider"];
    expect(() => parseBundle(raw)).toThrow(/array of numbers/);
  });
});

describe("applyConformal", () => {
  it("widens the bounds and leaves the median alone", async () => {
    const { applyConformal } = await import("../postprocess");
    const nutrition = {
      energy: { low: 200, median: 300, high: 400 },
      protein: { low: 10, median: 20, high: 30 },
      fat: { low: 5, median: 10, high: 15 },
      carbohydrate: { low: 20, median: 30, high: 40 },
      mass: { low: 100, median: 150, high: 200 },
      route: "absolute" as const,
    };

    const widened = applyConformal(nutrition, { keys: ["energy"], offsets: [50] });

    expect(widened.energy.low).toBe(150);
    expect(widened.energy.high).toBe(450);
    expect(widened.energy.median).toBe(300);
    // A target with no offset passes through untouched rather than being zeroed.
    expect(widened.protein).toEqual(nutrition.protein);
  });

  it("matches offsets by name, not by position", async () => {
    // Ordering comes from the contract on one side and a JSON file on the other. Zipping
    // them would widen energy by mass's miss.
    const { applyConformal } = await import("../postprocess");
    const nutrition = {
      energy: { low: 200, median: 300, high: 400 },
      protein: { low: 10, median: 20, high: 30 },
      fat: { low: 5, median: 10, high: 15 },
      carbohydrate: { low: 20, median: 30, high: 40 },
      mass: { low: 100, median: 150, high: 200 },
      route: "absolute" as const,
    };

    const widened = applyConformal(nutrition, { keys: ["mass", "energy"], offsets: [10, 50] });

    expect(widened.energy.high).toBe(450);
    expect(widened.mass.high).toBe(210);
  });

  it("never produces a negative bound", async () => {
    // A well-calibrated model can yield a negative offset, and a negative quantity of food
    // is not a thing.
    const { applyConformal } = await import("../postprocess");
    const nutrition = {
      energy: { low: 10, median: 20, high: 30 },
      protein: { low: 1, median: 2, high: 3 },
      fat: { low: 1, median: 2, high: 3 },
      carbohydrate: { low: 1, median: 2, high: 3 },
      mass: { low: 1, median: 2, high: 3 },
      route: "absolute" as const,
    };

    const widened = applyConformal(nutrition, { keys: ["energy"], offsets: [100] });
    expect(widened.energy.low).toBe(0);
  });
});
